// Generated by gencpp from file pure_pursuit_controller/cancelPath.msg
// DO NOT EDIT!


#ifndef PURE_PURSUIT_CONTROLLER_MESSAGE_CANCELPATH_H
#define PURE_PURSUIT_CONTROLLER_MESSAGE_CANCELPATH_H

#include <ros/service_traits.h>


#include <pure_pursuit_controller/cancelPathRequest.h>
#include <pure_pursuit_controller/cancelPathResponse.h>


namespace pure_pursuit_controller
{

struct cancelPath
{

typedef cancelPathRequest Request;
typedef cancelPathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct cancelPath
} // namespace pure_pursuit_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pure_pursuit_controller::cancelPath > {
  static const char* value()
  {
    return "88c671bcd6bd2eb3cdbe5da7918d3dff";
  }

  static const char* value(const ::pure_pursuit_controller::cancelPath&) { return value(); }
};

template<>
struct DataType< ::pure_pursuit_controller::cancelPath > {
  static const char* value()
  {
    return "pure_pursuit_controller/cancelPath";
  }

  static const char* value(const ::pure_pursuit_controller::cancelPath&) { return value(); }
};


// service_traits::MD5Sum< ::pure_pursuit_controller::cancelPathRequest> should match 
// service_traits::MD5Sum< ::pure_pursuit_controller::cancelPath > 
template<>
struct MD5Sum< ::pure_pursuit_controller::cancelPathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pure_pursuit_controller::cancelPath >::value();
  }
  static const char* value(const ::pure_pursuit_controller::cancelPathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pure_pursuit_controller::cancelPathRequest> should match 
// service_traits::DataType< ::pure_pursuit_controller::cancelPath > 
template<>
struct DataType< ::pure_pursuit_controller::cancelPathRequest>
{
  static const char* value()
  {
    return DataType< ::pure_pursuit_controller::cancelPath >::value();
  }
  static const char* value(const ::pure_pursuit_controller::cancelPathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pure_pursuit_controller::cancelPathResponse> should match 
// service_traits::MD5Sum< ::pure_pursuit_controller::cancelPath > 
template<>
struct MD5Sum< ::pure_pursuit_controller::cancelPathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pure_pursuit_controller::cancelPath >::value();
  }
  static const char* value(const ::pure_pursuit_controller::cancelPathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pure_pursuit_controller::cancelPathResponse> should match 
// service_traits::DataType< ::pure_pursuit_controller::cancelPath > 
template<>
struct DataType< ::pure_pursuit_controller::cancelPathResponse>
{
  static const char* value()
  {
    return DataType< ::pure_pursuit_controller::cancelPath >::value();
  }
  static const char* value(const ::pure_pursuit_controller::cancelPathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PURE_PURSUIT_CONTROLLER_MESSAGE_CANCELPATH_H
