// Generated by gencpp from file pure_pursuit_controller/cutPath.msg
// DO NOT EDIT!


#ifndef PURE_PURSUIT_CONTROLLER_MESSAGE_CUTPATH_H
#define PURE_PURSUIT_CONTROLLER_MESSAGE_CUTPATH_H

#include <ros/service_traits.h>


#include <pure_pursuit_controller/cutPathRequest.h>
#include <pure_pursuit_controller/cutPathResponse.h>


namespace pure_pursuit_controller
{

struct cutPath
{

typedef cutPathRequest Request;
typedef cutPathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct cutPath
} // namespace pure_pursuit_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pure_pursuit_controller::cutPath > {
  static const char* value()
  {
    return "8cd4fe60638b33ae09d3cdc05bf090c2";
  }

  static const char* value(const ::pure_pursuit_controller::cutPath&) { return value(); }
};

template<>
struct DataType< ::pure_pursuit_controller::cutPath > {
  static const char* value()
  {
    return "pure_pursuit_controller/cutPath";
  }

  static const char* value(const ::pure_pursuit_controller::cutPath&) { return value(); }
};


// service_traits::MD5Sum< ::pure_pursuit_controller::cutPathRequest> should match 
// service_traits::MD5Sum< ::pure_pursuit_controller::cutPath > 
template<>
struct MD5Sum< ::pure_pursuit_controller::cutPathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pure_pursuit_controller::cutPath >::value();
  }
  static const char* value(const ::pure_pursuit_controller::cutPathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pure_pursuit_controller::cutPathRequest> should match 
// service_traits::DataType< ::pure_pursuit_controller::cutPath > 
template<>
struct DataType< ::pure_pursuit_controller::cutPathRequest>
{
  static const char* value()
  {
    return DataType< ::pure_pursuit_controller::cutPath >::value();
  }
  static const char* value(const ::pure_pursuit_controller::cutPathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pure_pursuit_controller::cutPathResponse> should match 
// service_traits::MD5Sum< ::pure_pursuit_controller::cutPath > 
template<>
struct MD5Sum< ::pure_pursuit_controller::cutPathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pure_pursuit_controller::cutPath >::value();
  }
  static const char* value(const ::pure_pursuit_controller::cutPathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pure_pursuit_controller::cutPathResponse> should match 
// service_traits::DataType< ::pure_pursuit_controller::cutPath > 
template<>
struct DataType< ::pure_pursuit_controller::cutPathResponse>
{
  static const char* value()
  {
    return DataType< ::pure_pursuit_controller::cutPath >::value();
  }
  static const char* value(const ::pure_pursuit_controller::cutPathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PURE_PURSUIT_CONTROLLER_MESSAGE_CUTPATH_H
