// Generated by gencpp from file pure_pursuit_controller/cutPathRequest.msg
// DO NOT EDIT!


#ifndef PURE_PURSUIT_CONTROLLER_MESSAGE_CUTPATHREQUEST_H
#define PURE_PURSUIT_CONTROLLER_MESSAGE_CUTPATHREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pure_pursuit_controller
{
template <class ContainerAllocator>
struct cutPathRequest_
{
  typedef cutPathRequest_<ContainerAllocator> Type;

  cutPathRequest_()
    : safeWayPoint(0)  {
    }
  cutPathRequest_(const ContainerAllocator& _alloc)
    : safeWayPoint(0)  {
  (void)_alloc;
    }



   typedef int32_t _safeWayPoint_type;
  _safeWayPoint_type safeWayPoint;




  typedef boost::shared_ptr< ::pure_pursuit_controller::cutPathRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pure_pursuit_controller::cutPathRequest_<ContainerAllocator> const> ConstPtr;

}; // struct cutPathRequest_

typedef ::pure_pursuit_controller::cutPathRequest_<std::allocator<void> > cutPathRequest;

typedef boost::shared_ptr< ::pure_pursuit_controller::cutPathRequest > cutPathRequestPtr;
typedef boost::shared_ptr< ::pure_pursuit_controller::cutPathRequest const> cutPathRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pure_pursuit_controller::cutPathRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pure_pursuit_controller::cutPathRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pure_pursuit_controller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pure_pursuit_controller::cutPathRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pure_pursuit_controller::cutPathRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pure_pursuit_controller::cutPathRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pure_pursuit_controller::cutPathRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pure_pursuit_controller::cutPathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pure_pursuit_controller::cutPathRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pure_pursuit_controller::cutPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6702af91c1fe3106b1792026d5dd26ae";
  }

  static const char* value(const ::pure_pursuit_controller::cutPathRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6702af91c1fe3106ULL;
  static const uint64_t static_value2 = 0xb1792026d5dd26aeULL;
};

template<class ContainerAllocator>
struct DataType< ::pure_pursuit_controller::cutPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pure_pursuit_controller/cutPathRequest";
  }

  static const char* value(const ::pure_pursuit_controller::cutPathRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pure_pursuit_controller::cutPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 safeWayPoint\n\
\n\
";
  }

  static const char* value(const ::pure_pursuit_controller::cutPathRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pure_pursuit_controller::cutPathRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.safeWayPoint);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cutPathRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pure_pursuit_controller::cutPathRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pure_pursuit_controller::cutPathRequest_<ContainerAllocator>& v)
  {
    s << indent << "safeWayPoint: ";
    Printer<int32_t>::stream(s, indent + "  ", v.safeWayPoint);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PURE_PURSUIT_CONTROLLER_MESSAGE_CUTPATHREQUEST_H
