// Generated by gencpp from file rviz_textured_quads/TexturedQuad.msg
// DO NOT EDIT!


#ifndef RVIZ_TEXTURED_QUADS_MESSAGE_TEXTUREDQUAD_H
#define RVIZ_TEXTURED_QUADS_MESSAGE_TEXTUREDQUAD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>
#include <geometry_msgs/Pose.h>

namespace rviz_textured_quads
{
template <class ContainerAllocator>
struct TexturedQuad_
{
  typedef TexturedQuad_<ContainerAllocator> Type;

  TexturedQuad_()
    : image()
    , pose()
    , width(0.0)
    , height(0.0)
    , caption()
    , border_size(0.0)
    , border_color()  {
    }
  TexturedQuad_(const ContainerAllocator& _alloc)
    : image(_alloc)
    , pose(_alloc)
    , width(0.0)
    , height(0.0)
    , caption(_alloc)
    , border_size(0.0)
    , border_color(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _image_type;
  _image_type image;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef float _width_type;
  _width_type width;

   typedef float _height_type;
  _height_type height;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _caption_type;
  _caption_type caption;

   typedef float _border_size_type;
  _border_size_type border_size;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _border_color_type;
  _border_color_type border_color;




  typedef boost::shared_ptr< ::rviz_textured_quads::TexturedQuad_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rviz_textured_quads::TexturedQuad_<ContainerAllocator> const> ConstPtr;

}; // struct TexturedQuad_

typedef ::rviz_textured_quads::TexturedQuad_<std::allocator<void> > TexturedQuad;

typedef boost::shared_ptr< ::rviz_textured_quads::TexturedQuad > TexturedQuadPtr;
typedef boost::shared_ptr< ::rviz_textured_quads::TexturedQuad const> TexturedQuadConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rviz_textured_quads::TexturedQuad_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rviz_textured_quads::TexturedQuad_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rviz_textured_quads

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'rviz_textured_quads': ['/home/zlt/ros_ws/src/tensor_field_nav/rviz_textured_quads/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rviz_textured_quads::TexturedQuad_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rviz_textured_quads::TexturedQuad_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rviz_textured_quads::TexturedQuad_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rviz_textured_quads::TexturedQuad_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rviz_textured_quads::TexturedQuad_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rviz_textured_quads::TexturedQuad_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rviz_textured_quads::TexturedQuad_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ca357eef48c96ef31533ee760ce93902";
  }

  static const char* value(const ::rviz_textured_quads::TexturedQuad_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xca357eef48c96ef3ULL;
  static const uint64_t static_value2 = 0x1533ee760ce93902ULL;
};

template<class ContainerAllocator>
struct DataType< ::rviz_textured_quads::TexturedQuad_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rviz_textured_quads/TexturedQuad";
  }

  static const char* value(const ::rviz_textured_quads::TexturedQuad_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rviz_textured_quads::TexturedQuad_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/Image 	image  			# texture \n\
geometry_msgs/Pose 	pose   			# 6DOF pose of the center of the quad to be displayed\n\
float32 			width		    # physical width of the quad in Rviz unit (usually meters) \n\
float32 			height			# physical height of the quad in Rviz unit (usually meters) \n\
string 				caption		    # [OPTIONAL] text description to appear below the quad\n\
float32 			border_size     # [OPTIONAL] size of the quad border\n\
float32[] 			border_color    # [OPTIONAL] (r,g,b,a) color value of the quad border (Size = 4) \n\
================================================================================\n\
MSG: sensor_msgs/Image\n\
# This message contains an uncompressed image\n\
# (0, 0) is at top-left corner of image\n\
#\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of cameara\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
                     # If the frame_id here and the frame_id of the CameraInfo\n\
                     # message associated with the image conflict\n\
                     # the behavior is undefined\n\
\n\
uint32 height         # image height, that is, number of rows\n\
uint32 width          # image width, that is, number of columns\n\
\n\
# The legal values for encoding are in file src/image_encodings.cpp\n\
# If you want to standardize a new string format, join\n\
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n\
\n\
string encoding       # Encoding of pixels -- channel meaning, ordering, size\n\
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n\
\n\
uint8 is_bigendian    # is this data bigendian?\n\
uint32 step           # Full row length in bytes\n\
uint8[] data          # actual matrix data, size is (step * rows)\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::rviz_textured_quads::TexturedQuad_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rviz_textured_quads::TexturedQuad_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.image);
      stream.next(m.pose);
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.caption);
      stream.next(m.border_size);
      stream.next(m.border_color);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TexturedQuad_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rviz_textured_quads::TexturedQuad_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rviz_textured_quads::TexturedQuad_<ContainerAllocator>& v)
  {
    s << indent << "image: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.image);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "width: ";
    Printer<float>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
    s << indent << "caption: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.caption);
    s << indent << "border_size: ";
    Printer<float>::stream(s, indent + "  ", v.border_size);
    s << indent << "border_color[]" << std::endl;
    for (size_t i = 0; i < v.border_color.size(); ++i)
    {
      s << indent << "  border_color[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.border_color[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RVIZ_TEXTURED_QUADS_MESSAGE_TEXTUREDQUAD_H
