// Generated by gencpp from file rviz_textured_quads/TexturedQuadArray.msg
// DO NOT EDIT!


#ifndef RVIZ_TEXTURED_QUADS_MESSAGE_TEXTUREDQUADARRAY_H
#define RVIZ_TEXTURED_QUADS_MESSAGE_TEXTUREDQUADARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <rviz_textured_quads/TexturedQuad.h>

namespace rviz_textured_quads
{
template <class ContainerAllocator>
struct TexturedQuadArray_
{
  typedef TexturedQuadArray_<ContainerAllocator> Type;

  TexturedQuadArray_()
    : quads()  {
    }
  TexturedQuadArray_(const ContainerAllocator& _alloc)
    : quads(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::rviz_textured_quads::TexturedQuad_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::rviz_textured_quads::TexturedQuad_<ContainerAllocator> >::other >  _quads_type;
  _quads_type quads;




  typedef boost::shared_ptr< ::rviz_textured_quads::TexturedQuadArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rviz_textured_quads::TexturedQuadArray_<ContainerAllocator> const> ConstPtr;

}; // struct TexturedQuadArray_

typedef ::rviz_textured_quads::TexturedQuadArray_<std::allocator<void> > TexturedQuadArray;

typedef boost::shared_ptr< ::rviz_textured_quads::TexturedQuadArray > TexturedQuadArrayPtr;
typedef boost::shared_ptr< ::rviz_textured_quads::TexturedQuadArray const> TexturedQuadArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rviz_textured_quads::TexturedQuadArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rviz_textured_quads::TexturedQuadArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rviz_textured_quads

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'rviz_textured_quads': ['/home/zlt/ros_ws/src/tensor_field_nav/rviz_textured_quads/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rviz_textured_quads::TexturedQuadArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rviz_textured_quads::TexturedQuadArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rviz_textured_quads::TexturedQuadArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rviz_textured_quads::TexturedQuadArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rviz_textured_quads::TexturedQuadArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rviz_textured_quads::TexturedQuadArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rviz_textured_quads::TexturedQuadArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8682a94b73fe5b827efa6a32bb422a7a";
  }

  static const char* value(const ::rviz_textured_quads::TexturedQuadArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8682a94b73fe5b82ULL;
  static const uint64_t static_value2 = 0x7efa6a32bb422a7aULL;
};

template<class ContainerAllocator>
struct DataType< ::rviz_textured_quads::TexturedQuadArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rviz_textured_quads/TexturedQuadArray";
  }

  static const char* value(const ::rviz_textured_quads::TexturedQuadArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rviz_textured_quads::TexturedQuadArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "TexturedQuad[] quads \n\
================================================================================\n\
MSG: rviz_textured_quads/TexturedQuad\n\
sensor_msgs/Image 	image  			# texture \n\
geometry_msgs/Pose 	pose   			# 6DOF pose of the center of the quad to be displayed\n\
float32 			width		    # physical width of the quad in Rviz unit (usually meters) \n\
float32 			height			# physical height of the quad in Rviz unit (usually meters) \n\
string 				caption		    # [OPTIONAL] text description to appear below the quad\n\
float32 			border_size     # [OPTIONAL] size of the quad border\n\
float32[] 			border_color    # [OPTIONAL] (r,g,b,a) color value of the quad border (Size = 4) \n\
================================================================================\n\
MSG: sensor_msgs/Image\n\
# This message contains an uncompressed image\n\
# (0, 0) is at top-left corner of image\n\
#\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of cameara\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
                     # If the frame_id here and the frame_id of the CameraInfo\n\
                     # message associated with the image conflict\n\
                     # the behavior is undefined\n\
\n\
uint32 height         # image height, that is, number of rows\n\
uint32 width          # image width, that is, number of columns\n\
\n\
# The legal values for encoding are in file src/image_encodings.cpp\n\
# If you want to standardize a new string format, join\n\
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n\
\n\
string encoding       # Encoding of pixels -- channel meaning, ordering, size\n\
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n\
\n\
uint8 is_bigendian    # is this data bigendian?\n\
uint32 step           # Full row length in bytes\n\
uint8[] data          # actual matrix data, size is (step * rows)\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::rviz_textured_quads::TexturedQuadArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rviz_textured_quads::TexturedQuadArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.quads);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TexturedQuadArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rviz_textured_quads::TexturedQuadArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rviz_textured_quads::TexturedQuadArray_<ContainerAllocator>& v)
  {
    s << indent << "quads[]" << std::endl;
    for (size_t i = 0; i < v.quads.size(); ++i)
    {
      s << indent << "  quads[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::rviz_textured_quads::TexturedQuad_<ContainerAllocator> >::stream(s, indent + "    ", v.quads[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RVIZ_TEXTURED_QUADS_MESSAGE_TEXTUREDQUADARRAY_H
